version: '3.4'

services:
  db:
    image: mariadb
    volumes:
      - data:/var/lib/mysql:rw
    ports:
      - "6033:3306"
    environment:
      MYSQL_USER: breb0007
      MYSQL_PASSWORD: Azerty01
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: sae4
  php: 
    build: 
      context: ./
      target: sae4_php
    depends_on: 
      - db
    environment: 
      - PHP_INI_DIR=/usr/local/etc/php
    volumes:
      - ./:/srv/api:rw
      - ./docker/php/conf.d/dev.ini:/usr/local/etc/php/api.ini:rw
  api:
    build: 
      context: ./
      target: sae4_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/api/public:ro
    ports:
      - "8082:80"    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes: 
  data:

