version: '3.4'

services:
  db:
    image: mariadb
    volumes:
      - data:/var/lib/mysql:rw
    ports:
      - "6033:3306"
    environment:
      MYSQL_USER: breb0007
      MYSQL_PASSWORD: Azerty01
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: sae4

  php: 
    build: 
        context: ./
        target: sae4_php
    depends_on: 
      - db
    environment: 
      - PHP_INI_DIR=/usr/local/etc/php
    volumes:
      - ./:/srv/api:rw
      - ./docker/php/conf.d/dev.ini:/usr/local/etc/php/api.ini:rw


volumes: 
  data:

